### ISSUE TITLE
Packet ID 20 error?

### ISSUE THREAD

**Issue by KarlPro123** [dmulloy2/ProtocolLib#1475]
Debug paste link:
https://pastebin.com/dy7U55mH

Description and relevant errors:

So occasionally when players are opening chests (crates in my server, plugin SpecializedCrates (don't know if its that crate plugin or ProtocolLib), they get kicked with an error:
https://pastebin.com/MBEBgcZ4

But as SpecializedCrates doesn't appear to be using ProtocolLib's features, can it even be the problem here?
Tested with one of the latest Paper builds and ProtocolLib's dev builds.

**Comment by srnyx** [comment]
This is happening to me too when I sort chests with [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next).
*It may also be happening to other players on my server that don't use that mod, but not confirmed.*

**Comment by KarlPro123** [comment]
Yes I am using eco and EcoSkills, but how could it be an issue with these plugins?

**Comment by KarlPro123** [comment]
Definitely not that crate plugin, as it happens randomly as well.

**Comment by Guru2764** [comment]
I get various versions of the same issue, one player was kicked while smelting, and several players get kicked when opening crates. I will say that I am also use Specialized Crates and eco as well.

**Comment by srnyx** [comment]
I think this has something to do with eco's rate limiter, though I'm not 100% sure.
```yml
# Window items packets have the option to be run asynchronously. This may cause
# some bugs and is considered experimental, however it has been tested without
# any apparent issues. Enable this if performance is absolutely crucial or if you
# are experiencing severe display lag.
async-display:
  ratelimit:
    # If rate limit async display should be used.
    enabled: true
    # The amount of window items packets per timeframe needed to enable async display
    # for a specified player.
    cutoff: 4
    # The length of the timeframe in seconds.
    # Cutoff 5, Timeframe 1 means that if there are more than 5 window items packets
    # being sent per second for a player, then that player should have their packets
    # handled asynchronously.
    timeframe: 1
```
